<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/schema/1748884919412" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" targetNamespace="http://www.example.org/schema/1748884919412">
  <element name="addRequest">
    <complexType>
      <sequence>
        <element name="num1" type="integer"/>
                <element name="Num2" type="integer"/>
            </sequence>
    </complexType>
  </element>
  <element name="addResponse">
    <complexType>
      <sequence>
        <element name="result" type="integer"/>
      </sequence>
    </complexType>
  </element>
</schema>
